/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/BasicTable/ActionButton.vue')['default']
    BasicForm: typeof import('./src/components/BasicForm/index.vue')['default']
    BasicImage: typeof import('./src/components/BasicImage/index.vue')['default']
    BasicPagination: typeof import('./src/components/BasicPagination/index.vue')['default']
    BasicTable: typeof import('./src/components/BasicTable/index.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    Markdown: typeof import('./src/components/markdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
