# 1、工作流名称
name: GitHub Actions Build and Deploy

# 2、触发条件为：当master分支有push的时候
on:
  push:
    branches:
      - master

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write
# 3、创建工作流
jobs:
  build-and-deploy:  # 工作流名称
    runs-on: ubuntu-latest  # 依赖环境
    steps:  # 工作流步骤
      # step 1、 获取源码, 拉取仓库代码
      - name: Checkout  # 步骤名
        uses: actions/checkout@v4  # 使用插件 => https://github.com/actions/checkout
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      # step 2、安装依赖并打包
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      # step 3、部署到指定分支
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # 部署后提交到的分支
          folder: dist # 这里填打包好的目录名称